designersList:
   - designerId: DCAE
     designerHost: localhost
     designerPort: 8080
     designerPath: "/dcae"
     designerStateUrl: "dcae"
     designerProtocol: http
     designerDisplayOptions:
        context:
            displayName: "Monitor"
            displayContext: ["VF", "SERVICE"]
        top:
            displayName: "DCAE"
   - designerId: WORKFLOW
     designerHost: localhost
     designerPort: 9527
     designerPath: "/"
     designerStateUrl: "workflowDesigner"
     designerProtocol: http
     designerDisplayOptions:
        top:
            displayName: "WORKFLOW"